# Generated by Django 2.2.28 on 2023-06-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, verbose_name='username')),
                ('password', models.CharField(max_length=15, verbose_name='password')),
                ('role', models.CharField(max_length=15, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=100, verbose_name='pn')),
                ('pq', models.CharField(max_length=100, verbose_name='pq')),
                ('pp', models.CharField(max_length=100, verbose_name='pp')),
                ('pc', models.CharField(max_length=100, verbose_name='pc')),
                ('pi', models.CharField(max_length=100, verbose_name='pi')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('addr', models.CharField(max_length=100, verbose_name='address')),
                ('mobileno', models.CharField(max_length=100, verbose_name='mobileno')),
                ('mail', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.login')),
            ],
        ),
    ]
