# Generated by Django 2.2.28 on 2023-06-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('addr', models.CharField(max_length=100, verbose_name='address')),
                ('mobileno', models.CharField(max_length=100, verbose_name='mobileno')),
                ('mail', models.CharField(max_length=100, verbose_name='email')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.login')),
            ],
        ),
    ]
