# Generated by Django 2.2.28 on 2023-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhar',
            field=models.CharField(default=0, max_length=100, verbose_name='aadhar'),
        ),
    ]
