# Generated by Django 2.2.28 on 2023-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_auto_20230710_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pi',
            field=models.FileField(upload_to='images/', verbose_name='pi'),
        ),
    ]
