# Generated by Django 5.2.3 on 2025-06-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_auto_20230710_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name': 'Login', 'verbose_name_plural': 'Logins'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=15, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('staff', 'Staff')], max_length=15, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pc',
            field=models.CharField(max_length=100, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pi',
            field=models.FileField(upload_to='images/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pn',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pp',
            field=models.CharField(max_length=100, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pq',
            field=models.CharField(max_length=100, verbose_name='Product Quantity'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='aadhar',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='addr',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.login', verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mail',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobileno',
            field=models.CharField(max_length=100, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flower.login', verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(max_length=100, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=100, verbose_name='Status'),
        ),
        migrations.AlterModelTable(
            name='login',
            table='flower_login',
        ),
        migrations.AlterModelTable(
            name='products',
            table='flower_products',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='flower_staff',
        ),
        migrations.AlterModelTable(
            name='user',
            table='flower_user',
        ),
    ]
